# ============================================================
# Kafka Trace Producer ????
# ============================================================

# ---- Kafka ?? ----
# ???????IP:9092 (Kafka Broker ??)
kafka.bootstrap.servers=47.129.128.147:9092
kafka.topic=trace-data

# ---- ????? ----
kafka.acks=all
kafka.retries=5
kafka.enable.idempotence=true

# ---- Trace ???? ----
# ???? (??)
trace.period.ms=1
# ????
trace.batch.size=1000
# ??? (1000?)
trace.max.frames=1000000
# ??? (??)?50ms = ??20? = 2000?/??1000???83??
# ??????????? (0=??)
trace.send.interval.ms=50
# ??ID
trace.task.id=trace_001
